// Generated by BUCKLESCRIPT VERSION 6.0.1, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function domToCanvas(param) {
  if (param !== undefined) {
    return Caml_option.valFromOption(param);
  } else {
    return Pervasives.failwith("canvas undefined");
  }
}

function setFillStyle(prim, prim$1) {
  prim.fillStyle = prim$1;
  return /* () */0;
}

function setStrokeStyle(prim, prim$1) {
  prim.strokeStyle = prim$1;
  return /* () */0;
}

exports.domToCanvas = domToCanvas;
exports.setFillStyle = setFillStyle;
exports.setStrokeStyle = setStrokeStyle;
/* No side effect */
