// Generated by BUCKLESCRIPT VERSION 6.0.1, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Canvas$ReactHooksTemplate = require("./canvas.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Canvas$ReactHooksTemplate.make, { }), "root");

/*  Not a pure module */
